DROP TABLE SAILORS;
DROP TABLE BOATS;
DROP TABLE RESERVES;




CREATE TABLE SAILORS(
S_ID VARCHAR2(5) PRIMARY KEY,
NAME VARCHAR2(20),
RATING NUMBER(2),
AGE NUMBER(3));

CREATE TABLE BOATS(
B_ID VARCHAR2(5) PRIMARY KEY,
B_NAME VARCHAR2(20),
COLOR VARCHAR2(15));

CREATE TABLE RESERVES(
S_ID VARCHAR2(5) REFERENCES SAILORS(S_ID),
B_ID VARCHAR2(5) REFERENCES BOATS(B_ID),
DAY VARCHAR2(10));


INSERT ALL
	INTO SAILORS VALUES('S0001','Arijit',7,20)
	INTO SAILORS VALUES('S0002','Arnab',10,62)
	INTO SAILORS VALUES('S0003','Subham',5,40)
	INTO SAILORS VALUES('S0004','Aditi',10,31)
	INTO SAILORS VALUES('S0005','Aviree',5,27)
	INTO SAILORS VALUES('S0006','Tiyasha',9,37)
	INTO SAILORS VALUES('S0007','Aniket',8,45)
	INTO SAILORS VALUES('S0008','Shounak',4,69)
	INTO SAILORS VALUES('S0009','Madhurima',4,10)
	INTO SAILORS VALUES('S0010','Triasa',10,18)
	INTO SAILORS VALUES('S0011','Tarun',9,70)
SELECT * FROM DUAL;

INSERT ALL
	INTO BOATS VALUES('B0001','Titanic','Gray')
	INTO BOATS VALUES('B0002','Xail','Blue')
	INTO BOATS VALUES('B0003','Tataboats','Green')
	INTO BOATS VALUES('B0004','Lightray','Red')
	INTO BOATS VALUES('B0005','Ravengers','Red')
	INTO BOATS VALUES('B0006','Queenjet','Red')
	INTO BOATS VALUES('B0007','Warship','Green')
	INTO BOATS VALUES('B0008','Starktech','Black')
	INTO BOATS VALUES('B0009','Citari','Black')
	INTO BOATS VALUES('B0010','Timex','Yellow')
	INTO BOATS VALUES('B0011','Xjet','Blue')
SELECT * FROM DUAL;

INSERT ALL
	INTO RESERVES VALUES('S0001','B0006','Monday')
	INTO RESERVES VALUES('S0002','B0002','Tuesday')
	INTO RESERVES VALUES('S0003','B0001','Sunday')
	INTO RESERVES VALUES('S0004','B0005','Friday')
	INTO RESERVES VALUES('S0005','B0004','Monday')
	INTO RESERVES VALUES('S0006','B0044','Sunday')
	INTO RESERVES VALUES('S0007','B0003','Friday')
	INTO RESERVES VALUES('S0008','B0006','Monday')
	INTO RESERVES VALUES('S0009','B0010','Tuesday')
	INTO RESERVES VALUES('S0010','B0009','Friday')
	INTO RESERVES VALUES('S0011','B0008','Monday')
SELECT * FROM DUAL;


a)SELECT BOATS.COLOR FROM BOATS INNER JOIN RESERVES ON BOATS.B_ID=RESERVES.B_ID WHERE RESERVES.S_ID=(SELECT S_ID  FROM SAILORS WHERE NAME LIKE 'Tarun');

b)SELECT S_ID,B_ID FROM RESERVES WHERE DAY LIKE 'Monday';

c)SELECT B_ID,B_NAME FROM BOATS WHERE COLOR LIKE 'Red' OR COLOR LIKE 'Green';

d)DELETE FROM RESERVES WHERE S_ID IN (SELECT S_ID FROM SAILORS WHERE AGE>60);
    DELETE FROM SAILORS WHERE AGE >60;





------------------2ND QUESTION---------------------------------------------------------------------------



DROP TABLE STUDENT;
DROP TABLE TAUGHTBY;
DROP TABLE TEACHER;
DROP TABLE SUBJECT;



CREATE TABLE TEACHER(
TID VARCHAR2(6) PRIMARY KEY,
NAME VARCHAR2(25),
DEPT VARCHAR2(20));

CREATE TABLE SUBJECT(
SUBNO VARCHAR2(6) PRIMARY KEY,
SUBTITLE VARCHAR2(30));

CREATE TABLE TAUGHTBY(
TID VARCHAR2(5) REFERENCES TEACHER(TID),
SUBNO VARCHAR2(6) REFERENCES SUBJECT(SUBNO) ,
PRIMARY KEY(TID,SUBNO)
);

CREATE TABLE STUDENT(
ROLLNO NUMBER(3) PRIMARY KEY,
SNAME VARCHAR2(20),
CITY VARCHAR2(20));

INSERT ALL
	INTO TEACHER VALUES('T0001','Rabindranath','Physics')
	INTO TEACHER VALUES('T0002','Amiya','CSE')
	INTO TEACHER VALUES('T0003','Pradipta','Humanities')
	INTO TEACHER VALUES('T0004','Supriyo','Biology')
	INTO TEACHER VALUES('T0005','Surojit','Humanities')	
	INTO TEACHER VALUES('T0006','Sodesh','Mathmatics')	
	INTO TEACHER VALUES('T0007','Sourav','Humanities')	
	INTO TEACHER VALUES('T0008','Kaustav','Humanities')	
	INTO TEACHER VALUES('T0009','Avik','Physics')	
	INTO TEACHER VALUES('T0010','Partha','Physics')	
	INTO TEACHER VALUES('T0011','Bokan','Biology')	
	INTO TEACHER VALUES('T0012','Debasis','CSE')
	INTO TEACHER VALUES('T0013','Biplob','Mathmatics')	
SELECT * FROM DUAL;

INSERT ALL
	INTO SUBJECT VALUES('S0001','Image Processing')
	INTO SUBJECT VALUES('S0002','Thermodynamics')
	INTO SUBJECT VALUES('S0003','Microbiology')
	INTO SUBJECT VALUES('S0004','DBMS')
	INTO SUBJECT VALUES('S0005','Linear Algebra')
	INTO SUBJECT VALUES('S0006','Calculus')
	INTO SUBJECT VALUES('S0007','English')
	INTO SUBJECT VALUES('S0009','Geography')
	INTO SUBJECT VALUES('S0010','Philosophy')
	INTO SUBJECT VALUES('S0011','Fluid Mechanics')
	INTO SUBJECT VALUES('S0012','Biochemistry')
	INTO SUBJECT VALUES('S0013','History')
SELECT * FROM DUAL;


INSERT ALL
	 INTO TAUGHTBY VALUES('T0001','S0002')
	 INTO TAUGHTBY VALUES('T0002','S0001')
	 INTO TAUGHTBY VALUES('T0003','S0007')
	 INTO TAUGHTBY VALUES('T0004','S0003')
	 INTO TAUGHTBY VALUES('T0005','S0009')
	 INTO TAUGHTBY VALUES('T0006','S0006')
	 INTO TAUGHTBY VALUES('T0007','S0013')
	 INTO TAUGHTBY VALUES('T0008','S0010')
	 INTO TAUGHTBY VALUES('T0009','S0002')
	 INTO TAUGHTBY VALUES('T0010','S0011')
	 INTO TAUGHTBY VALUES('T0011','S0012')
	 INTO TAUGHTBY VALUES('T0012','S0004')
	 INTO TAUGHTBY VALUES('T0013','S0005')
SELECT * FROM DUAL;



INSERT ALL
	INTO STUDENT VALUES(25,'Arijit','Haripal')
	INTO STUDENT VALUES(15,'Arnab','Budgebudge')
	INTO STUDENT VALUES(16,'Subham','Tollygaunge')
	INTO STUDENT VALUES(22,'Aditi','Joka')
	INTO STUDENT VALUES(18,'Aviree','Dumdum')
	INTO STUDENT VALUES(17,'Tiyasha','Kolkata')
	INTO STUDENT VALUES(21,'Aniket','Kolkata')
	INTO STUDENT VALUES(19,'Shounak','Kolkata')
	INTO STUDENT VALUES(20,'Madhurima','Howrah')
	INTO STUDENT VALUES(10,'Triasa','Howrah')
	INTO STUDENT VALUES(23,'Tarun','Kolkata')
	INTO STUDENT VALUES(24,'Sumedha','Kolkata')
SELECT * FROM DUAL;




1.SELECT TEACHER.NAME FROM TEACHER INNER JOIN TAUGHTBY ON TEACHER.TID =TAUGHTBY.TID 
WHERE TAUGHTBY.SUBNO=(SELECT SUBNO FROM SUBJECT WHERE SUBTITLE LIKE 'Thermodynamics');

2.UPDATE SUBJECT SET SUBTITLE='RDBMS' WHERE SUBTITLE LIKE 'DBMS';

3. SELECT ROLLNO,SNAME FROM STUDENT WHERE CITY LIKE 'Kolkata' AND ROLLNO BETWEEN 20 AND 25;

4. SELECT * FROM STUDENT WHERE CITY LIKE 'Kolkata' ORDER BY ROLLNO;
