1. UPDATE PRODUCT_MASTER SET REORDERLVL=80 WHERE DESCRIPTION ='Shirts';
2.UPDATE PRODUCT_MASTER SET SELLPRICE=SELLPRICE+SELLPRICE*0.1;
3.UPDATE SALESMAN_MASTER SET YTDSALES =YTDSALES+35 WHERE SALESMANNO ='S00003';
4.UPDATE SALES_ORDER_DETAILS SET QTYDISP=QTYODERED;
5.UPDATE CLIENT_MASTER SET PINCODE =400001 WHERE CITY='Mumbai';
6.UPDATE PRODUCT_MASTER SET REORDERLVL=